dist: bionic
sudo: required
language: node_js
node_js:
  - "8.11.3"

cache:
  directories:
    - "node_modules"

before_install:
  # Install Ethereum Tools
  - sudo add-apt-repository ppa:ethereum/ethereum -y
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo apt-get install solc
  # Install Ganache & Truffle
  - npm i -g ganache-cli truffle@4.1.8
  - ganache-cli &>/dev/null &
  # Install IPFS
  - wget "https://dist.ipfs.io/go-ipfs/v0.4.9/go-ipfs_v0.4.9_linux-amd64.tar.gz" -O /tmp/ipfs.tar.gz
  - pushd . && cd $HOME/bin && tar -xzvf /tmp/ipfs.tar.gz && popd
  - export PATH="$HOME/bin/go-ipfs:$PATH"
  - ipfs init
  - ipfs daemon &
  - sleep 15
  - curl http://localhost:5001/api/v0/id

  # Install ocaml
  - sudo apt-get install -y wget gcc ocaml opam libzarith-ocaml-dev m4 pkg-config zlib1g-dev libffi-dev
#  - opam init -y --comp=4.06.1
#  - opam init -y --comp=4.05.0
  - opam init -y
  - eval $(opam config env)
  - opam update
  - opam install -y cryptokit yojson ctypes ctypes-foreign

install:
  - npm run fixperms
  - npm install
  - cd ocaml-offchain/interpreter
  - make
  - cd ../..
  - npm run compile
  - npm run deploy
  - cd wasm-ports/samples
  - sh deploy.sh
  - cd ../..

script:
  - cd ocaml-offchain/interpreter
  - sh runtests.sh
  - cd ../..
  - NODE_ENV='production' npm run test
  - node cli/index.js wasm-client/config-jit.json --batch -c "start solve" &
  - sleep 15
  - mocha wasm-ports/samples/test

